# Generated by Django 4.0 on 2022-01-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('taille', models.IntegerField()),
                ('localisation', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('publish', models.BooleanField(default=False)),
                ('annee', models.DateField(null=True)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.societe')),
            ],
        ),
    ]
